In [2]:
import numpy as np

In [5]:
A1 = np.arange(12).reshape(3,4)
A2 = np.arange(12,24).reshape(3,4)
A2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#mathematical operations works here like *,/,+,-,%,^
A1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
#relational operator like <,>,==,!=,<=,>=
A2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
#Vector operator
A1 + A2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])