In [5]:
import numpy as np

In [ ]:
print(np.array([1,2,3]))

[1 2 3]


In [ ]:
print(np.array([[1,2,3],[1,2,7],[3,5,7]]))

In [ ]:
print(np.array([[[1,2,7],[2,4,8]],[[3,7,3],[3,7,2]]]))

[[[1 2 7]
  [2 4 8]]

 [[3 7 3]
  [3 7 2]]]


In [ ]:
print (np.array([1,2,4],dtype=float))

[1. 2. 4.]


In [ ]:
print (np.array([1,2,0],dtype=bool))

[ True  True False]


In [ ]:
print (np.array([1,2,4],dtype=complex))

[1.+0.j 2.+0.j 4.+0.j]


In [ ]:
print(np.arange(1,101,9))

[  1  10  19  28  37  46  55  64  73  82  91 100]


In [ ]:
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
print(np.random.random((3,4)))

[[0.6716506  0.8000463  0.73407346 0.47558039]
 [0.68139726 0.55217089 0.18065295 0.45680001]
 [0.57256503 0.59739493 0.51180013 0.36731993]]


In [50]:
print(np.linspace(-10,10,6))

[-10.  -6.  -2.   2.   6.  10.]


In [45]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
