In [2]:
import numpy as np

In [14]:
A1 = np.random.random((3,3))
A1 = np.round(A1 * 100)
A1

array([[ 3., 34., 98.],
       [76., 73., 92.],
       [45., 39., 78.]])

In [17]:
print(np.max(A1))
print(np.min(A1))
print(np.sum(A1))
print(np.prod(A1))
print(np.max(A1,axis=0))
print(np.max(A1,axis=1))


98.0
3.0
538.0
698428979015040.0
[76. 73. 98.]
[98. 92. 78.]


In [ ]:
#statastics
print(np.mean(A1))
print(np.median(A1))
print(np.std(A1))
print(np.var(A1))

59.77777777777778
73.0
29.453457739958242
867.5061728395061


In [ ]:
#triganometric functions
print(np.sin(A1))

[[ 0.14112001  0.52908269 -0.57338187]
 [ 0.56610764 -0.67677196 -0.77946607]
 [ 0.85090352  0.96379539  0.51397846]]


In [31]:
A2 = np.arange(12).reshape(3,4)
A3 = np.arange(12,24).reshape(4,3)

print(A2)
print("\n")
print(A3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [26]:
#dot product
print(np.dot(A2,A3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [35]:
#log 
print(np.log(A2))
#exponential
print("\n")
print(np.exp(A1))

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]


[[2.00855369e+01 5.83461743e+14 3.63797095e+42]
 [1.01480039e+33 5.05239363e+31 9.01762841e+39]
 [3.49342711e+19 8.65934004e+16 7.49841700e+33]]


C:\Users\Dell\AppData\Local\Temp\ipykernel_19500\2267749676.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(A2))


In [39]:
print(np.round(np.random.random((2,3))*100))
print("\n")
print(np.floor(np.random.random((2,3))*100))
print("\n")
print(np.ceil(np.random.random((2,3))*100))

[[45. 99. 63.]
 [76. 26. 74.]]


[[64. 67.  3.]
 [31. 16. 72.]]


[[80. 28. 18.]
 [ 7. 68. 65.]]
