In [5]:
import numpy as np

In [19]:
A1 = np.arange(12)
A2 = np.arange(12).reshape(4,3)
A3 = np.arange(27).reshape(3,3,3)
print(A3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [7]:
A1
for i in A1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [9]:
for i in A2:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [10]:
for i in np.nditer(A3):
    print(i)


0
1
2
3
4
5
6
7


In [12]:
np.transpose(A2)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [20]:
A3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])