In [2]:
import numpy as np

In [3]:
A1 = np.arange(12)
A2 = np.arange(16).reshape(4,4)
A3 = np.arange(8).reshape(2,2,2)
A2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
A3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
A3[1,1,0]

np.int64(6)

In [37]:
#Slicing
A3[::-1]

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [40]:
A2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [47]:
A2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [48]:
A2[1,::3]

array([4, 7])

In [53]:
A2[1::2,1::1]

array([[ 5,  6,  7],
       [13, 14, 15]])

In [54]:
A3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
A3=np.arange(27).reshape(3,3,3)
A3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
A3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])